## Travis CI Script by Caio Oliveira aka Caio99BR <caiooliveirafarias0@gmail.com>
# For Open-PS2-Loader
## Thanks to:
# - izdubar@psx-scene and jimmikaelkael@psx-scene
#   <http://psx-scene.com/forums/f150/%5Blinux%5D-opl-compile-guides-63749/>
# - Bat Rastard@psx-scene and doctorxyz@psx-scene
#   <http://psx-scene.com/forums/f150/2015-linux-mint-vm-creation-opl-compiling-guide-ps2sdk-127047/index3.html#post1169435>
# - and a lot of people around internet :)

dist: trusty
sudo: required
language: c
cache: ccache

services:
  - docker

## Fix make_changelog.sh
git:
  depth: 9999999

before_install:
  ## Save env dir
  #- cd ../
  #- export TRAVIS_ENV_DIR=$(pwd)
  
  ## Get docker image
  - docker pull akuhak/ps2toolchain:new_gcc
  - docker ps
  
  ## Save repo name
  - export NEW_REPO_SLUG=$(echo ${TRAVIS_REPO_SLUG} | cut -f 1 -d "/")

  ## Make CCache good to us
  - export PATH="/usr/lib/ccache:${PATH}"

install:
  ## Dependencies

before_script:
  ## Make cleanup, just for prevent anything
  - docker run -d akuhak/ps2toolchain:new_gcc bash -c "while true; do sleep 5; done" > container_id

  ## Clone ps2sdk
  - docker exec -t `cat container_id` bash -c "git clone https://github.com/uyjulian/ps2sdk"
  - docker exec -t `cat container_id` bash -c "cd /ps2sdk/; git reset --hard origin/uyjworking; git checkout uyjworking"
  - docker exec -t `cat container_id` bash -c "cd /ps2sdk/; make --silent install"

  - docker exec -t `cat container_id` bash -c "git clone https://github.com/sp193/ps2sdk-ports"
  - docker exec -t `cat container_id` bash -c "cd /ps2sdk-ports/zlib/; make install"
  - docker exec -t `cat container_id` bash -c "cd /ps2sdk-ports/libpng/; make install"
  - docker exec -t `cat container_id` bash -c "cd /ps2sdk-ports/libjpeg/; make install"
  - docker exec -t `cat container_id` bash -c "cd /ps2sdk-ports/freetype2/; make install"

  ## Set up the environment
  - export GSKIT=${PS2DEV}/gsKit
  
after_success:
  ## Export some variables
  #- docker run akuhak/new_gcc /bin/bash -c "export OPL_VERSION=$(make oplversion)"
  #- docker run akuhak/new_gcc /bin/bash -c "export OPL_UP_LAST_BUILD=$(curl --upload-file ${TRAVIS_BUILD_DIR}/OPNPS2LD-${OPL_VERSION}-${NEW_REPO_SLUG}.ZIP https://transfer.sh/OPNPS2LD-${OPL_VERSION}-${NEW_REPO_SLUG}-NIGHTLY${TRAVIS_BUILD_NUMBER}.zip)"
  #- docker run akuhak/new_gcc /bin/bash -c "export OPL_LANG_UP_LAST_BUILD=$(curl --upload-file ${TRAVIS_BUILD_DIR}/OPNPS2LD_LANGS-${OPL_VERSION}.zip https://transfer.sh/OPNPS2LD_LANGS-${OPL_VERSION}-NIGHTLY${TRAVIS_BUILD_NUMBER}.zip)"
  #- docker run akuhak/new_gcc /bin/bash -c "export OPL_DATE=$(date +%d'/'%m'/'%Y)"

  ## Configure TravisCI git
  #- git config --global user.email "builds@travis-ci.org"
  #- git config --global user.name "Travis-CI"

  ## Clone my gh-page
  #- git clone --quiet --branch=gh-pages https://${GH_TOKEN}@github.com/Caio99BR/Open-PS2-Loader ${TRAVIS_ENV_DIR}/gh-pages/ > /dev/null
  #- cd ${TRAVIS_ENV_DIR}/gh-pages/

  ## Let's upload latest build to gh-page!
  #- bash ${TRAVIS_ENV_DIR}/gh-pages/index-download-make.sh


